openapi: '3.0.0'
info:
  version: 1.0.0
  title: Northforge Studio Documentation
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /calls:
    get:
      summary: List all calls
      operationId: listCalls
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of calls
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create call
      operationId: createCall
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /calls/{callId}:
    get:
      summary: Get call details
      operationId: showCallById
      parameters:
        - name: callId
          in: path
          required: true
          description: The id of the call to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /appointments:
    get:
      summary: List appointments
      operationId: listAppointments
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of appointments
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointments'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create appointment
      operationId: createAppointment
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Call:
      required:
        - id
        - caller
      properties:
        id:
          type: integer
          format: int64
        caller:
          type: string
        purpose:
          type: string
    Calls:
      type: array
      items:
        $ref: '#/components/schemas/Call'
    Appointment:
      required:
        - id
        - time
      properties:
        id:
          type: integer
          format: int64
        time:
          type: string
        customer:
          type: string
    Appointments:
      type: array
      items:
        $ref: '#/components/schemas/Appointment'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string